### ISSUE TITLE
An error in Version 2023-01-20 (v1.4.0) prevents the network accelerator from working

### ISSUE THREAD

**Issue by reeerasda** [0blu/WinterspringLauncher#16]
![捕获11](https://user-images.githubusercontent.com/124072936/215816900-06806e03-ba76-45fe-9aec-e93e08603549.PNG)

**Comment by 0blu** [comment]
Were you able to use the WinterspringLauncher before that?
Is this error new?

**Comment by reeerasda** [comment]
> 在那之前你能使用WinterspringLauncher吗？ 这个错误是新的吗？
Version 2022-12-04 was used properly yesterday, but an error occurred after update today.
Now open the old and new versions of the software, the system will be automatically updated directly, there will be errors when using.

**Comment by mosikejiroujuan** [comment]
![1](https://user-images.githubusercontent.com/124110487/215936953-a528f422-f7d7-478e-af66-3cdd1fa2c31d.png)
![2](https://user-images.githubusercontent.com/124110487/215936962-c59bf5a5-0e6c-44c0-adbb-c5923cca612e.png)
![3](https://user-images.githubusercontent.com/124110487/215936970-db784077-90fb-465b-9dff-5870b319a54a.png)

**Comment by mosikejiroujuan** [comment]
WinterspringLauncher  Error in running after replacing the file Unable to log in to the game

**Comment by mosikejiroujuan** [comment]
Please help solve it. I hope to log in as soon as possible. Thank you very much

**Comment by 0blu** [comment]
Sorry to hear that, apparently the windows **pre-release** launcher has bug.
Please use the latest stable version <https://github.com/0blu/WinterspringLauncher/releases/tag/1.3.0>.

To fix the missing files you have to trigger a redownload of `hermes-proxy`.
Just remove the `version.txt` inside `hermes-proxy`.

**Comment by mosikejiroujuan** [comment]
Thank you very much for your reply. Let me try it


烟台君通美达汽车销售有限公司
鞠海丰 （集团销售部）
电话：0535-6021888
传真：0535-6608222
手机：13696388456
          
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/1/2023 13:25 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [0blu/WinterspringLauncher] An error in Version 2023-01-20 (v1.4.0) prevents the network accelerator from working (Issue #16) |

Sorry to hear that, apparently the windows pre-release launcher has bug.
Please use the latest stable version https://github.com/0blu/WinterspringLauncher/releases/tag/1.3.0.

To fix the missing files you have to trigger a redownload of hermes-proxy.
Just remove the version.txt inside hermes-proxy.

**Comment by mosikejiroujuan** [comment]
Before sending this question, I have tested the two logins on December 4 and January 23, both of which are the same.

All are useless

**Comment by reeerasda** [comment]
> 很抱歉听到这个消息，显然 Windows**预发布**启动器有错误。 请使用最新的稳定版本https://github.com/0blu/WinterspringLauncher/releases/tag/1.3.0。
> 
> 要修复丢失的文件，您必须触发重新下载`hermes-proxy`. 只需删除`version.txt`内部`hermes-proxy`。

@0blu 
I just downloaded the initiator again through the address you provided, but an error was still reported after startup.
![Uploading 微信截图_20230201165026.png…]()
![微信截图_20230201165123](https://user-images.githubusercontent.com/124072936/215995559-2cafd641-9dd6-47ca-96cc-728892bf2474.png)
![微信截图_20230201165146](https://user-images.githubusercontent.com/124072936/215995562-988722de-6379-43c2-a0e3-d2017e9e9816.png)
