### ISSUE TITLE
Launcher failing today, worked fine yesterday.

### ISSUE THREAD

**Issue by pooserver** [0blu/WinterspringLauncher#17]
![image](https://user-images.githubusercontent.com/123998131/215861161-9f0bf2d3-61ea-4b56-8bfb-636225a0ca92.png)

haven't changed anything

**Comment by pooserver** [comment]
I even downloaded the updated Hermes-proxy and copied my Account Data and still fails

**Comment by pooserver** [comment]
Figured I'd wait to hear back from you, but my next step is going to be just re-downloading the entire WSlauncher and copying my addons/ account data over.

**Comment by pooserver** [comment]
Reinstalled the launcher from scratch and copied my old addons/wtf/account data and it all works again. Not sure why it stopped working from one day to the next but its all good now.

**Comment by 0blu** [comment]
Weird, it said something with about an `permission error`, did you change anything in your windows settings?
