### ISSUE TITLE
Running on Parallel on Mac and getting this error when trying to open launcher

### ISSUE THREAD

**Issue by mikemccallum87** [0blu/WinterspringLauncher#18]
![Screenshot 2023-01-31 at 16 43 23](https://user-images.githubusercontent.com/121958407/215872477-78bc47a9-73ba-4858-996d-a7c67658f350.png)

**Comment by 0blu** [comment]
You have to move it elsewhere.
`//Mac` is a "network" path, synced with your host. World of Warcraft does not support it.
You can to place it somewhere on `C:/`


If you are using an m1 mac, you can also try to use the native version for better performance.
<https://github.com/0blu/WinterspringLauncher/releases/tag/1.4.0>

**Comment by mikemccallum87** [comment]
Ah brilliant yeah its working now, unfortunately I have the mac model just
before the M1 chip so unfortunately the native version is not working for
me.

Thank you for your help!
