### ISSUE TITLE
Virus Detected?

### ISSUE THREAD

**Issue by 8EightySixed6** [0blu/WinterspringLauncher#2]
Unable to download as a virus is detected. WTH

**Comment by 0blu** [comment]
Were you the guy with BitDefender on Discord?

I can ensure you that there is nothing malicious going on.
[VirusTotal](https://www.virustotal.com/gui/file/8128a1bee0cbef04d8b99296a04c329f23d9a32df4ebb1bbc5a222ba87200c41) also does not report any problems with the latest release.


Can you please provide more information:
- What did you exactly download? (All official downloads are on the [release page](https://github.com/0blu/EverlookClassicLauncher/releases))
- What antivirus are you using?
- What did the antivirus say?
