### ISSUE TITLE
zsh: bad CPU type in executable: /Applications/Winterspring Launcher.app/WinterspringLauncher

### ISSUE THREAD

**Issue by seathasky** [0blu/WinterspringLauncher#21]
Mac version is not working for me on my Intel based Mac Pro. I assume the Mac version is solo for ARM based Macs, any chance we can get an Intel version?

**Comment by SangrealArthas** [comment]
Having the same issue

**Comment by 0blu** [comment]
Currently there are no plans for an Intel version

**Comment by seathasky** [comment]
No worries, upgraded to an M2 Mac recently
