### ISSUE TITLE
Unable to unlock shift/cmd modifiers on MacOS

### ISSUE THREAD

**Issue by seathasky** [0blu/WinterspringLauncher#24]
Normally with the standard WoW client on Mac you can use 
"defaults write com.blizzard.worldofwarcraft disable-expose-fix -bool YES"

This will allow for shift modifiers to work with my Razer Naga. How would I go about fixing this with this client?

**Comment by 0blu** [comment]
Sorry for not answering your issue.
Were you able to solve the issue?

**Comment by seathasky** [comment]
> Sorry for not answering your issue. Were you able to solve the issue?

Unfortunately no. This issue still exists

**Comment by 0blu** [comment]
Oh okay, how can I test the issue?
Just bind an action to SHIFT+E?

**Comment by seathasky** [comment]
Correct, shift anything, control+anything on Mac OS

**Comment by 0blu** [comment]
And inside your razor menu for your mouse you bound "Control+E" onto a single button for example?

**Comment by 0blu** [comment]
I also have a razer naga (pro).
I used `defaults write com.blizzard.worldofwarcraft disable-expose-fix -bool YES` inside the terminal and it seems to work for me.

**Comment by seathasky** [comment]
> I also have a razer naga (pro). I used `defaults write com.blizzard.worldofwarcraft disable-expose-fix -bool YES` inside the terminal and it seems to work for me. (_Tested it with `SHIFT+3` and `CONTROL+3`_)

Awesome, I just did the same and that worked XD ty!

**Comment by 0blu** [comment]
Great 😄
