### ISSUE TITLE
Wrong Download Path in Terminal App on Mac. 

### ISSUE THREAD

**Issue by badname9000** [0blu/WinterspringLauncher#34]
When I open the terminal launcher unix file. it tries downloading from the wrong or outdated downloads page: https://download.wowdl.net/WoW_Classic_1.14.0.40618_macOS.zip

when it actually should start downloading from this link: 
https://download.wowdl.net/downloadFiles/Clients/WoW_Classic_1.14.0.40618_macOS_new.zip

any chance to fix this? Seems like an easy fix, if one can code, which i can't...

**Comment by 0blu** [comment]
You are right. It was changed somehow.
I will fix it a on the upcoming weekend.

My goal is to release a gui version in the future too.

**Comment by badname9000** [comment]
thanks mate! the plans sound awesome. I would really enjoy the game natively on my M1 air.  

I really got to get an understanding of the coding behind something like this :) thanks for your work mate; a UI would be fantastic for beginners.

**Comment by 0blu** [comment]
Thanks for reporting the issue 😃.
I fixed it in the [new version](https://github.com/0blu/WinterspringLauncher/releases).

The ui will be tracked in another ticket/issue.
