### ISSUE TITLE
 FAIL_UNKNOWN_ACCOUNT

### ISSUE THREAD

**Issue by bobaipeng** [0blu/WinterspringLauncher#5]
why i got this?
13:11:57 |  Server  | BnetTcpSession  | Accepting connection from 127.0.0.1:56503.
13:11:58 |  Network | AuthClient      | C P>S | Connecting to auth server... (realmlist addr: 51.91.104.108:3724)
13:11:59 |  Error   | AuthClient      | Login failed. Reason: FAIL_UNKNOWN_ACCOUNT

**Comment by 0blu** [comment]
The current build is working for me.
- Do you have 2FA enabled?
- Maybe you entered your account credentials wrong

**Comment by bobaipeng** [comment]
> The current build is working for me.
> 
> * Do you have 2FA enabled?
> * Maybe you entered your account credentials wrong

I  enble the 2FA,must  disable it?

**Comment by 0blu** [comment]
Will be further tracked by https://github.com/WowLegacyCore/HermesProxy/issues/66
