### ISSUE TITLE
[BUG] "HermesSettings" field in winterspring-launcher-config.json DOES NOT override HermesProxy.config 

### ISSUE THREAD

**Issue by gibeiro** [0blu/WinterspringLauncher#51]
#### Steps to reproduce

1. In `winterspring-launcher-config.json`, fill "HermesSettings" for a item in the "KnownServers" list.
2. Launch `WinterspringLauncher.exe` and "Start Game" with the desired server config.

#### Expectation
HermesProxy will run with the settings added in `winterspring-launcher-config.json` under the "HermesSettings" field.
```
  "KnownServers": [
    {
      "Name": "Sanctuary",
      "RealmlistAddress": "logon.sanctuarywow.com",
      "UsedInstallation": "Default 1.14.2 installation",
      "HermesSettings": {
        "RestPort": "8082"
      }
    }
  ]
```
In my case, I specify RestPort as 8082.

#### Outcome
HermesProxy runs with the default values from `HermesProxy.config`
<img width="683" alt="image" src="https://github.com/0blu/WinterspringLauncher/assets/15379409/e4df8a8d-5fc8-4794-ae82-14686379afe6">

**Comment by 0blu** [comment]
Thanks for the report
