### ISSUE TITLE
Casting sound continues playing after casting

### ISSUE THREAD

**Issue by tronics-glitch** [0blu/WinterspringLauncher#6]
Sometimes, casting sound continues playing after I finish the cast.
This can happen to any spells.
Very rarely, the casting effects also stays on (example hands on fire when casting fireball).
When the issue happens, the only way to stop the casting sound is to log out, or to die.

**Comment by 0blu** [comment]
Hermes Issue: Further tracked by https://github.com/WowLegacyCore/HermesProxy/issues/104
