### ISSUE TITLE
Waiting to send SMSG_SET_PROFICIENCY (10026).

### ISSUE THREAD

**Issue by tronics-glitch** [0blu/WinterspringLauncher#7]
Sometimes I get stuck on loading screen while logging in with a repeating message in the console that says:
22:42:34 |  Network | WorldClient     | C<P S | Waiting to send SMSG_SET_PROFICIENCY (10026).
22:42:34 |  Network | WorldClient     | C<P S | Waiting to send SMSG_SET_PROFICIENCY (10026).
22:42:34 |  Network | WorldClient     | C<P S | Waiting to send SMSG_SET_PROFICIENCY (10026).
22:42:34 |  Network | WorldClient     | C<P S | Waiting to send SMSG_SET_PROFICIENCY (10026).
22:42:34 |  Network | WorldClient     | C<P S | Waiting to send SMSG_SET_PROFICIENCY (10026).
22:42:34 |  Network | WorldClient     | C<P S | Waiting to send SMSG_SET_PROFICIENCY (10026).
22:42:34 |  Network | WorldClient     | C<P S | Waiting to send SMSG_SET_PROFICIENCY (10026).

This appears to have started after I installed an addon called Aux: https://www.curseforge.com/wow/addons/aux/files/all?filter-game-version=2020709689%3A8958

When the issue happens, the only way to fix it is to close game and console, and relaunch.

**Comment by 0blu** [comment]
That's a known random bug of HermesProxy itself, you have to restart the launcher.
It most likely has nothing to do with your addons.
